### PR TITLE
Added multiprocessing to contig cleaner

### PR DESCRIPTION
**Pull request by bogemad**
Hi Jon,

Thanks for such a useful annotation pipeline.

I had a couple of genomes with _a lot_ of contigs so I added multiprocessing to funannotate contig cleaner to speed things up. I have it working on my system using both mummer and minimap2. 

Thought that it might be useful to share.

Cheers,

Daniel

### CODE REVIEW

**Comment by nextgenusfs** [comment]
Thanks Daniel!  Can you confirm with a test set that you get same results with cpu=1 versus something larger?  The reason I never tried over multiple processors was that I iterated through from shortest to longest and dropping those that were duplicated as they were found -- maybe that was just me being conservative and it wouldn't matter.

An additional way could speed it up would be to perhaps use the `minimap2` python bindings `mappy`, which would eliminate the subprocess calls to `minimap2` maybe storing the fasta files in something like `StringIO` so they didn't need to be written to file before alignment could then also speed things up?  Something like load all contigs into dictionary, sort by length, then loop through shortest to largest do alignment of current contig against all larger contigs with StringIO/mappy, stop when N50 is reached (or whatever setting that might be).

**Comment by nextgenusfs** [comment]
Note that I would be happy to drop mummer -- fewer dependencies the better.  minimap2 didn't exist when this project was started -- but I use minimap2 now for pretty much all alignment tasks.

**Comment by hyphaltip** [comment]
yes I think minimap2 seems like the right thing for contig to contig comparisons.

**Comment by bogemad** [comment]
Ok I updated the script to include a more graceful exit on Ctrl-C/SIGINT and ran using mummer/minimap2 with both 1 and 32 cpus. Minimap2 was much faster and produced the same output for this dataset. Output is below...

```
$ funannotate clean --cpus 32 -i test.fa -o test.clean.mum.cpu1.fa --method mummer
-----------------------------------------------
40 input contigs, 38 larger than 500 bp, N50 is 2,063,676 bp
Checking duplication of 32 contigs shorter than N50
-----------------------------------------------
contig182 appears duplicated: 99% identity over 100% of the contig. contig length: 2948 
contig183 appears duplicated: 99% identity over 100% of the contig. contig length: 2407 
contig171 appears duplicated: 99% identity over 100% of the contig. contig length: 5594 
contig175 appears duplicated: 98% identity over 100% of the contig. contig length: 4610 
contig178 appears duplicated: 99% identity over 100% of the contig. contig length: 4123 
contig170 appears duplicated: 99% identity over 99% of the contig. contig length: 5737 
contig185 appears duplicated: 99% identity over 100% of the contig. contig length: 1209 
contig186 appears duplicated: 100% identity over 99% of the contig. contig length: 1019 
contig177 appears duplicated: 99% identity over 100% of the contig. contig length: 4256 
contig180 appears duplicated: 99% identity over 100% of the contig. contig length: 3259 
-----------------------------------------------
40 input contigs; 38 larger than 500 bp; 10 duplicated; 28 written to file

$ funannotate clean --cpus 1 -i test.fa -o test.clean.mum.cpu1.fa --method mummer
-----------------------------------------------
40 input contigs, 38 larger than 500 bp, N50 is 2,063,676 bp
Checking duplication of 32 contigs shorter than N50
-----------------------------------------------
contig186 appears duplicated: 100% identity over 99% of the contig. contig length: 1019 
contig185 appears duplicated: 99% identity over 100% of the contig. contig length: 1209 
contig183 appears duplicated: 99% identity over 100% of the contig. contig length: 2407 
contig182 appears duplicated: 99% identity over 100% of the contig. contig length: 2948 
contig180 appears duplicated: 99% identity over 100% of the contig. contig length: 3259 
contig178 appears duplicated: 99% identity over 100% of the contig. contig length: 4123 
contig177 appears duplicated: 99% identity over 100% of the contig. contig length: 4256 
contig175 appears duplicated: 98% identity over 100% of the contig. contig length: 4610 
contig171 appears duplicated: 99% identity over 100% of the contig. contig length: 5594 
contig170 appears duplicated: 99% identity over 99% of the contig. contig length: 5737 
-----------------------------------------------
40 input contigs; 38 larger than 500 bp; 10 duplicated; 28 written to file

$ grep -c '>' test.fa
40
$ grep -c '>' test.clean.mum.cpu1.fa
28
$ grep -c '>' test.clean.mum.cpu32.fa
28

$ diff -s test.clean.mum.cpu32.fa test.clean.mum.cpu1.fa
Files test.clean.mum.cpu32.fa and test.clean.mum.cpu1.fa are identical
```

```
$ funannotate clean --cpus 32 -i test.fa -o test.clean.mini.cpu32.fa --method minimap2
-----------------------------------------------
40 input contigs, 38 larger than 500 bp, N50 is 2,063,676 bp
Checking duplication of 32 contigs shorter than N50
-----------------------------------------------
contig175 appears duplicated: 100% identity over 99% of the contig. contig length: 4610
contig186 appears duplicated: 100% identity over 99% of the contig. contig length: 1019
contig171 appears duplicated: 100% identity over 100% of the contig. contig length: 5594
contig177 appears duplicated: 100% identity over 100% of the contig. contig length: 4256
contig185 appears duplicated: 100% identity over 97% of the contig. contig length: 1209
contig170 appears duplicated: 100% identity over 100% of the contig. contig length: 5737
contig180 appears duplicated: 99% identity over 100% of the contig. contig length: 3259
contig182 appears duplicated: 100% identity over 99% of the contig. contig length: 2948
contig178 appears duplicated: 100% identity over 99% of the contig. contig length: 4123
contig183 appears duplicated: 100% identity over 100% of the contig. contig length: 2407
-----------------------------------------------
40 input contigs; 38 larger than 500 bp; 10 duplicated; 28 written to file

$ funannotate clean --cpus 1 -i test.fa -o test.clean.mini.cpu1.fa --method minimap2
-----------------------------------------------
40 input contigs, 38 larger than 500 bp, N50 is 2,063,676 bp
Checking duplication of 32 contigs shorter than N50
-----------------------------------------------
contig186 appears duplicated: 100% identity over 99% of the contig. contig length: 1019
contig185 appears duplicated: 100% identity over 97% of the contig. contig length: 1209
contig183 appears duplicated: 100% identity over 100% of the contig. contig length: 2407
contig182 appears duplicated: 100% identity over 99% of the contig. contig length: 2948
contig180 appears duplicated: 99% identity over 100% of the contig. contig length: 3259
contig178 appears duplicated: 100% identity over 99% of the contig. contig length: 4123
contig177 appears duplicated: 100% identity over 100% of the contig. contig length: 4256
contig175 appears duplicated: 100% identity over 99% of the contig. contig length: 4610
contig171 appears duplicated: 100% identity over 100% of the contig. contig length: 5594
contig170 appears duplicated: 100% identity over 100% of the contig. contig length: 5737
-----------------------------------------------
40 input contigs; 38 larger than 500 bp; 10 duplicated; 28 written to file

$ grep -c '>' test.fa
40

$ grep -c '>' test.clean.mini.cpu32.fa
28

$ grep -c '>' test.clean.mini.cpu1.fa
28

$ diff -s test.clean.mini.cpu32.fa test.clean.mini.cpu1.fa
Files test.clean.mini.cpu32.fa and test.clean.mini.cpu1.fa are identical
```

**Comment by bogemad** [comment]
Also compared with master funannotate clean script:

```
$ git clone https://github.com/nextgenusfs/funannotate.git
Cloning into 'funannotate'...
remote: Enumerating objects: 120, done.
remote: Counting objects: 100% (120/120), done.
remote: Compressing objects: 100% (60/60), done.
remote: Total 4988 (delta 82), reused 92 (delta 60), pack-reused 4868
Receiving objects: 100% (4988/4988), 31.33 MiB | 6.94 MiB/s, done.
Resolving deltas: 100% (3600/3600), done.
$ funannotate/funannotate clean -i test.fa -o test.clean.mini.serial.fa --method minimap2
-----------------------------------------------
40 input contigs, 38 larger than 500 bp, N50 is 2,063,676 bp
Checking duplication of 32 contigs shorter than N50
-----------------------------------------------
contig186 appears duplicated: 100% identity over 99% of the contig. contig length: 1019
contig185 appears duplicated: 100% identity over 97% of the contig. contig length: 1209
contig183 appears duplicated: 100% identity over 100% of the contig. contig length: 2407
contig182 appears duplicated: 100% identity over 99% of the contig. contig length: 2948
contig180 appears duplicated: 99% identity over 100% of the contig. contig length: 3259
contig178 appears duplicated: 100% identity over 99% of the contig. contig length: 4123
contig177 appears duplicated: 100% identity over 100% of the contig. contig length: 4256
contig175 appears duplicated: 100% identity over 99% of the contig. contig length: 4610
contig171 appears duplicated: 100% identity over 100% of the contig. contig length: 5594
contig170 appears duplicated: 100% identity over 100% of the contig. contig length: 5737
-----------------------------------------------
40 input contigs; 38 larger than 500 bp; 10 duplicated; 28 written to file

$ diff -s test.clean.mini.serial.fa test.clean.mini.cpu32.fa 
Files test.clean.mini.serial.fa and test.clean.mini.cpu32.fa are identical
```

**Comment by nextgenusfs** [comment]
Fantastic, thanks @bogemad.

**Pull request merged**
