### PR TITLE
expose ability to use a premade diamond database

### PR DESCRIPTION
**Pull request by photocyte**
Hi there,

I'm trying to wrap funannotate in a Nextflow pipeline so I can more fully parallelize it across our HPC (running on some large eukaryotic genomes, so it helps).  These changes enable the prot2genome.py subscript to be able to use a premade diamond database.  Since the new parameter is exposed as an optional parameter to `runDiamond()`, it should be a transparent change to the rest of funannotate.

### CODE REVIEW

**Comment by hyphaltip** [comment]
This is a great opportunity - I would be happy to see this added in and can test nextflow runs we do as well. I think we need to integrate more validity statistics about the result of a run perhaps too to provide more checkpoints from a run too? Eg I don't launch a interproscan run until I'm sure the annotation quality was pretty good?

**Comment by photocyte** [comment]
My Nextflow pipeline is still pretty early - perhaps I should wait until it finishes before I confirm the additional parallelization is definitely faster! But if it's useful to others, I'd be happy to post what I have so far. 

So far I've only been wrapping / bypassing the early steps of funannotate (e.g. repeat modeling & masking using the RepeatModeler Docker/Singularity image directly), and haven't yet gotten to the downstream functional annotation.  I haven't spent too much time trying to figure out how to configure Nextflow pipelines to have maximum flexibility across different clusters/cloud executors, but Nextflow core (https://nf-co.re) has some mature examples of that.

Regarding checkpoints: it's pretty straightforward to wrap the parts of funannotate where there are separate funannotate subcommands.  Alternatively, when there is situation where there is single file/parameter that changes the internal execution of a subcommand (e.g. `--protein_alignments` vs `--protein_evidence` for `funannotate predict`), and there is pretty much a separate subcommand / script that handles that branch in the internal execution (`funannotate util prot2genome` and `./funannotate/aux_scripts/funannotate.py`), its not too bad to implement that in Nextflow.

For validity statistics, it seems like a quagmire to really be changing the process execution a lot in Nextflow based on how things are going (it is possible, through operators like https://www.nextflow.io/docs/latest/operator.html#branch), but in the limiting case of simply erroring out if a given validity statistics fails, that is straightforward to implement.

**Comment by hyphaltip** [comment]
yeah I'm curious what level of granularity is really worth the effort for this tool - MAKER for example is much more parallelized by running every contig and each analysis set as a separate job - it scales really well + with MPI. I can see the same for this requires a new way to look at the project flow I think, as you have already started.

 I have a few other projects we are moving to nextflow so I will investigate as well and happy to help.

**Comment by hyphaltip** [comment]
But lets def try and make sure this is on a new branch? thoughts @nextgenusfs ?

**Comment by photocyte** [comment]
For the latest commit on the PR (https://github.com/nextgenusfs/funannotate/pull/408/commits/84405e5e9063fe7ed6ff536110b28104a0161786), that isn't strictly speaking related to using a diamond database.  But, I think it is very important parameter to include for PASA, as if not included, high-quality transcripts can be thrown away simple because they have some natural variation near the splice site.  In fact, the PASA developer includes it for their sample runs: https://github.com/PASApipeline/PASApipeline/blob/master/sample_data/sqlite.confs/alignAssembly.config .

**Comment by photocyte** [comment]
Is a 96% identity not enough? My point was, the `80` parameter, will throw away alignments with > 80 identity (I presume, due to how exonerate is calculating internally - maybe it is each segment has to be above >80).  A better solution would be to have `funannotate-p2g.py` expose that parameter externally.

**Comment by nextgenusfs** [comment]
I don't know how the pct identity is calculated internally in exonerate or how you arrived at 96%. At least as far as I thought I understood it, --percent 80 should be keeping only those protein2genome alignments > 80% (whether that is each HSP or total I'm less sure on). 

How many more alignments did you get if you set at 40?

**Comment by photocyte** [comment]
The aforementioned 96% was the value output by the `ryo` parameter for Exonerate. I was mimicking the exonerate cmd that funannotate uses: `exonerate --model p2g --showvulgar no --showalignment no --showquerygff no --showtargetgff yes --maxintron 500000 --percent 80 --ryo "AveragePercentIdentity: %pi\n" PNM_00009.pep.fa softmasked.Pnm1.1s314237p1.1.fasta
`

I don't have a direct comparison for the number of alignments between a proteome aligned at `40` vs `80` - I was just troubleshooting with a single gene I'm interested in - and that gene wasn't producing alignments to a closely related paralog on a different scaffold.  

But, beyond the seeming unintended feature that high-identity alignments are thrown away,  just on first principles: 80% sequence identity (presumably referring to the peptide-to-peptide alignment) is really two quite closely related proteins.  Probably works well in well-studied lineages e.g. mammals, but, my feeling is that is too stringent for a general parameter for lineages not well represented in Swissprot.

**Comment by nextgenusfs** [comment]
Using only curated high pct identity is actually the point of this in my opinion, the goal should be to use only proteins alignments that have actual experimental evidence otherwise you end up using ab initio predictions to train the gene predictors —  not what we are after here.

**Comment by photocyte** [comment]
If I revert https://github.com/nextgenusfs/funannotate/pull/408/commits/0fbd4f8c744fd4626240e144aac40aeaf683b01c and https://github.com/nextgenusfs/funannotate/pull/408/commits/a0f38b208e71834f8963b73534fcf269c21bf695, would this PR be acceptable?  I believe the other changes in the PR are pretty vanilla. I can make another issue or PR to discuss the other issues.

But regarding the protein alignments parameter: I understand the GIGO principle - and wanting to avoid bad protein alignments, however I don't think that is at play here.  In my case, the `80` vs `40` parameter is the difference between a _de novo_ transcriptome derived peptide, aligning to a non-expressed paralog at a separate locus, or not. That seems like valuable actual experimental, "good data", to me, as it helps the _ab initio_ predictor (via hints) at a locus without experimental transcript evidence.  I wouldn't call this a case of _ab initio_ predictions being used to train the _ab initio_ gene predictors. It seems to me that the _ab initio_ predictor training funannotate does a fair amount of gene model filtering that is a bit more intelligent than a percent identity cutoff, which is a bit arbitrary, and, if my issue is correct, currently is overly zealous in filtering out quite high percent identity alignments.

My understanding is there are three places the protein alignment evidence is used: 
(1) the _ab initio_ training itself - training is just on the gene models from PASA or BUSCO (discussed well at our issue here: https://github.com/nextgenusfs/funannotate/issues/283), but the protein evidence is used amongst other evidence and heuristics to filter those gene models. 
 
(2) the protein alignment evidence is passed as a hint to Augustus - influencing the post-training-prediction, rather than the training itself.

And (3), there is also downstream use of the alignments by EvidenceModeler.  The exact depth and type of protein alignment evidence that is optimal in training Augustus or other _ab initio_ predictors, and as a hint to Augustus, and as weighted evidence in Evidence Modeler, I think is hard to judge and probably a bit different for the three cases. 

Finally (4), protein alignments are my go to for manually troubleshooting gene models (after PASA gene models) - so having a more lenient cutoff for the initial alignment is helpful.

The overall point is: overly stringent alignments is perhaps a help in the training step, but could hurt in the Augustus hints, the use in EvidenceModeler, and the use downstream in manual refinement & checking of select gene models.  That is my gut feel anyway, in the absence of something like a systematic sweeps all the protein inputs / alignment score filtering / weight parameters to see if certain combinations are especially good.

**Comment by nextgenusfs** [comment]
It’s an easy fix to just add the pident as an option and users can adjust as they see fit. 

My day job has been busy the last month and haven’t had a chance to do much of anything with funannotate. I was really close to a python 3 port working which about a month ago I was hoping to finish (in the python3 branch). I had told myself the next release would be py3.  But I need to look at these changes and test them before merging but it seems mostly confined to p2g step which is basically separate so I don’t thinkn I’ll be a big deal to merge. I will see if I can find some time today.

**Comment by nextgenusfs** [comment]
I pushed some of these to the python3 branch. Not tested yet. https://github.com/nextgenusfs/funannotate/commit/df4e7f0e9a2a7b01baa6c25e6f261733db574ea0

**Pull request closed without merging**
